fix: make MongoBulkWriteError conform to CRUD spec
mongodb/node-mongodb-native pull request #2621
Opened 2020-11-13 19:46 UTC by HanaPearlman

This PR makes `BulkWriteError` conform to the CRUD spec by adding the necessary fields required by the spec tests to the class and renames `BulkWriteError` to `MongoBulkWriteError`.

NODE-1989, NODE-2331

2020-11-17 20:38 UTC, emadum requested changes
LGTM! I think we can take this PR as an opportunity to tighten up some properties which are currently optional but don't need to be.

2020-11-17 20:38 UTC, emadum commented on src/bulk/common.ts
>    constructor(error?: AnyError, result?: BulkWriteResult) {
I think we should make the `error` and `result` properties/constructor options non-optional. These errors are always constructed with both arguments.

2020-11-17 20:38 UTC, emadum commented on src/bulk/common.ts
> +    this.modifiedCount = result?.modifiedCount || 0;
Don't need to provide a default here, `modifiedCount` is already guaranteed to be a number in `BulkWriteResult`.

2020-11-17 20:38 UTC, emadum commented on src/bulk/common.ts
> +  insertedCount?: number;
If `result` isn't optional (see lower comment) none of these new properties need to be optional either.

2020-11-17 21:05 UTC, nbbeeken approved these changes
Eric's suggestions seem to cover it, lgtm!

2020-11-18 14:09 UTC, mbroadst approved these changes
LGTM

2020-11-18 14:36 UTC, emadum approved these changes

2020-11-19 14:26 UTC, merged