fix: use require instead of readFileSync for driver.version (#2937)
mongodb/node-mongodb-native pull request #2652
Opened 2020-12-02 13:03 UTC by aherlihy

This is the solution mongosh is currently using in my fork of the driver. I don't know if you want to use this directly or some other solution. For more details see NODE-2937

2020-12-02 16:02 UTC, kmahar commented
(@aherlihy I just added people for review myself so should be all good)

2020-12-02 16:18 UTC, emadum requested changes
there are a few lint errors from the now-unused vars:

```
warning  'readFileSync' is defined but never used  @typescript-eslint/no-unused-vars
warning  'resolve' is defined but never used       @typescript-eslint/no-unused-vars
```

2020-12-04 12:51 UTC, aherlihy commented
Right! Sorry I missed that, should be done @emadum

2020-12-04 13:19 UTC, emadum approved these changes

2020-12-04 15:13 UTC, nbbeeken approved these changes

2020-12-04 15:52 UTC, merged