test: Add unified spec runner scaffolding
mongodb/node-mongodb-native pull request #2689
Opened 2021-01-08 22:48 UTC by nbbeeken

Using the unfied spec test schema this scaffolding
outlines the structure of a unified runner. Most tests
are skipped by the runOn requirements or not implemented
errors thrown by empty operation functions.

NODE-2287

## Description

**What changed?**

**Are there any files to ignore?**

2021-01-13 13:08 UTC, durran requested changes

2021-01-13 21:33 UTC, nbbeeken commented on test/functional/unified-spec-runner/entities.ts
> +  getClient(key: string): UnifiedMongoClient {
I agree, each of these methods also means we'd have a different stack trace for each one even though it is the same error, I've consolidated the helpers into `getEntity` and `mapOf` and I think it's friendly enough we don't need the bespoke methods any more, getEntity with a type param works nicely!

2021-01-14 15:29 UTC, emadum approved these changes
Suggested a few typo fixes in comments but LGTM 👍

2021-01-14 15:29 UTC, emadum commented on test/functional/unified-spec-runner/operations.ts
> +          // each key/value expectation can be is a special op
```suggestion
          // each key/value expectation can be a special op
```

2021-01-14 15:32 UTC, durran approved these changes
Nice refactor! LGTM

2021-01-15 15:23 UTC, merged