fix: update estimated document count for v1 api
mongodb/node-mongodb-native pull request #2764
Opened 2021-03-24 21:27 UTC by emadum

NODE-3074

2021-03-29 17:19 UTC, nbbeeken requested changes
Looks good, just a few nits:

2021-03-29 17:19 UTC, nbbeeken commented on test/unit/sessions/collection.test.js
> +    it.skip('does not mutate command options', {
Should we just change this to use a different operation?

2021-03-29 17:19 UTC, nbbeeken commented on test/functional/crud_spec.test.js
> +                this.skip();
There shouldn't be anymore 'not implemented.' errors in the runner I believe so we can drop this.

2021-03-29 17:19 UTC, nbbeeken commented on src/operations/estimated_document_count.ts
> +  constructor(collection: Collection, options?: EstimatedDocumentCountOptions) {
```suggestion
  constructor(collection: Collection, options: EstimatedDocumentCountOptions = {}) {
```
Just a preference to use this, and then drop the if stmt below, feel free to disagree ofc.

2021-03-30 14:21 UTC, nbbeeken approved these changes
lgtm!

2021-04-07 19:22 UTC, durran approved these changes
LGTM

2021-04-07 20:58 UTC, merged