chore: reintroduce nodejs fermium testing
mongodb/node-mongodb-native pull request #2775
Opened 2021-04-01 16:17 UTC by nbbeeken

Somehow I dropped fermium testing, bringing it back here.

2021-04-01 16:48 UTC, emadum approved these changes

2021-04-02 18:07 UTC, emadum requested changes
Can we restrict the tests that fail on fermium to `node<14` and add a ticket to fix them?

2021-04-02 19:40 UTC, nbbeeken commented
> Can we restrict the tests that fail on fermium to `node<14` and add a ticket to fix them?

Excellent idea, went and did that, so the remaining errors are on macos only and look like the typical flakiness we usually see there.

2021-04-02 21:29 UTC, emadum approved these changes

2021-04-05 14:56 UTC, merged