Changed '.equal()' to '.strictEqual()' in examples
mongodb/node-mongodb-native pull request #2798
Opened 2021-05-05 11:33 UTC by lMartin3

asserts.equal() is deprecated, changed it to assert.strictEqual().

## Description

**What changed?**
README.md - Changed the examples so they used asserts.strictEqual() instead of asserts.equal() (which is deprecated).

**Are there any files to ignore?**
No

2021-05-12 16:24 UTC, nbbeeken approved these changes
Seems like a good idea to modernize the examples, thanks for your contribution!

2021-05-12 18:59 UTC, dariakp approved these changes

2021-05-12 19:34 UTC, emadum requested changes
Thanks for this PR! Just one small suggestion.

2021-05-12 19:34 UTC, emadum commented on README.md
> +    assert.strictEqual(err, null);
```suggestion
    assert.ifError(err);
```

I think we could go a bit further and update the error checks to use `assert.ifError` here, which seems like the most idiomatic approach.

2021-05-12 21:20 UTC, wa-Nadoo commented
IMHO the better approach is to enforce strict assertion mode for all methods. Just replace `const assert = require('assert')` with  `const assert = require('assert').strict` or  `const assert = require('assert/strict')`. In strict assertion mode all non-strict methods behave like strict methods. More info is available here: https://nodejs.org/api/assert.html#assert_strict_assertion_mode.

2021-09-01 15:24 UTC, nbbeeken commented
Closing due to inactivity and target branch needs updating, 3.7 is now the current 3.x branch

2021-09-01 15:24 UTC, closed without merging