refactor(NODE-3356): Remove logs that duplicate command monitoring functionality
mongodb/node-mongodb-native pull request #2851
Opened 2021-06-17 21:18 UTC by dariakp

## Description

NODE-3356

2021-06-17 21:23 UTC, nbbeeken approved these changes

2021-06-20 14:11 UTC, durran approved these changes
I like this refactoring. It was always expected with the command monitoring spec that a logger itself would be registering itself to all our monitoring if the users wanted easy debug, and this is how we originally implemented it in the Ruby driver at least and I believe there was discussion for the same for Node in the past that just got deprioritised. This puts us in the right direction - nice job.

2021-06-21 14:27 UTC, emadum requested changes
LGTM but one of the Logger tests is failing in CI.

2021-06-21 19:25 UTC, dariakp commented
> LGTM but one of the Logger tests is failing in CI.

Oh that's weird, I could have sworn I saw them pass earlier; I'll look into it, thanks for the catch! @emadum

2021-06-21 20:35 UTC, emadum approved these changes

2021-06-21 20:45 UTC, merged