test(NODE-3358): Command monitoring objects hold internal state references
mongodb/node-mongodb-native pull request #2860
Opened 2021-06-24 21:40 UTC by W-A-James

## Description
Test clean-up

**What changed?**
test/functional/apm.test.js

2021-06-24 21:42 UTC, dariakp approved these changes
Thank you!

2021-06-25 14:36 UTC, dariakp requested changes

2021-06-25 14:36 UTC, dariakp commented on test/functional/apm.test.js
> +    beforeEach(function (done) {
@W-A-James Let's make the same change here as on the other PR per Eric's comment

2021-06-25 14:48 UTC, dariakp approved these changes
Thanks!

2021-06-25 16:12 UTC, nbbeeken approved these changes

2021-06-25 19:32 UTC, merged