fix(NODE-3380): perform retryable write checks against server
mongodb/node-mongodb-native pull request #2861
Opened 2021-06-25 00:20 UTC by emadum

NODE-3380

2021-06-28 17:20 UTC, nbbeeken requested changes

2021-06-28 17:20 UTC, nbbeeken commented on lib/core/sdam/topology.js
> +    const willRetryWrite =
On line 676 we have similiar logic to update and we discussed some code clarity while we're here:
```
    const currentlyNotRetrying = !args.retrying;
    const retryWrites = !!options.retryWrites;
    const hasSession = !!options.session;
    const supportsRetryableWrites = server.supportsRetryableWrites;
    const notInTransaction = !options.session.inTransaction();
    const notExplaining = options.explain === undefined;
    const willRetryWrite =
      currentlyNotRetrying &&
      retryWrites &&
      hasSession &&
      supportsRetryableWrites &&
      notInTransaction &&
      notExplaining;
```

2021-06-28 17:58 UTC, nbbeeken approved these changes

2021-06-29 13:18 UTC, durran approved these changes

2021-06-29 16:49 UTC, merged