fix(NODE-3386): listCollections result type definition
mongodb/node-mongodb-native pull request #2866
Opened 2021-06-28 19:42 UTC by nbbeeken

The listCollections cursor now has a generic that defaults to a flexible CollectionInfo type. Typescript can't change a return type bases on a runtime boolean so I show example usage in the added types test of how one can use the API pretty succinctly.

2021-06-28 20:41 UTC, addaleax commented
> Typescript can't change a return type bases on a runtime boolean

Fwiw, it can come pretty close: [TypeScript playground](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQDkEFsoHswA2AnqgN7CqWpjZQBcqAzhDOAOYDcwAvsKJLEQpUAMQCuBAgEkwcXKigAPaGAAmjDLXzEyFKjRwNmrMJz2UIRAA70mLdl17AkBBIw0ARAEa6qqAiDMAMK4klBIECD4jAAUcCAE0DAMAErhuDCqADzG7AA0qAhgRAB8BbhWkdEMpNS0APKERAwsYmjcAJQMAAowuFiBUFmYONpEANoAuiVcfgHBoQThVWCx8YmwqemZOfamBUWl5ZVRqzV1OI3EDIgEjO1dqL39g1nikjJyUzPm-oEQITCEVOawSSS2SAy2Vy+0KxTKqAqK0Y5wMUCuzVQXlwoSgRVQnR6fQG9yyMXe0lk8gAPppRk0Ot9ZlR5gDFssQXEwZtUGlITsYWwDvDjsjUQ0mgxsbj8YSnsTXuSJJS5KhaSM8Azvr4-FQYFAIGIYGB5S97gA6fWMUIANygMXGpDRdAA5IoXQVLDYGC6AF4u7iTDrMyi8JxuIhgJCoOBiKMrGM4mIdHWUSGrCAXTU6AC8hQA7ggQJmYmAoPnUN5k+bWYClsDojFSNwCrU0RiWjA2gSOsHfunmDHleBVXmEIXi6hS+XK15q7X2Q3Vk2W2Qsx2Ywg7g8+34B5m44wjWgxxOS2WK1WOjX-nWOY3m6315LUABZBAQAAWlqKqn6ydQEpUAABnNABWHtdyoAB6aCszGcZgMmc0vSgDhUFg1AsgAWlQNgQDtDRUMYJBWEqBQYD6GBfljSQR1wRDkNQ9DMJw6h5FgKjfkww9j0YlDrDQjC4LYrdrQoqiNB4IA)

2021-06-29 14:10 UTC, nbbeeken commented
Oo thanks for the insight, I'll give that a try

2021-06-29 15:59 UTC, addaleax approved these changes

2021-07-02 16:01 UTC, emadum approved these changes
LGTM 👍

2021-07-08 18:08 UTC, dariakp requested changes
small typo, otherwise LGTM :)

2021-07-08 18:08 UTC, dariakp commented on test/types/list_collections.test-d.ts
> +// Testings each argument variation
```suggestion
// Testing each argument variation
```

2021-07-09 16:24 UTC, nbbeeken commented
Rebased, should clear up the unrelated error in the last CI run

2021-07-09 17:27 UTC, merged