fix(connection): report more helpful error with unsupported authMechanism in initial handshake
mongodb/node-mongodb-native pull request #2876
Opened 2021-07-01 20:51 UTC by vkarpov15

## Description

I haven't been able to repro this locally, but there's a user that ran into this case at Automattic/mongoose#10377. Figured this change is sufficiently straightforward that it's worthwhile to patch without digging into it much further.

**What changed?**

Added a quick check for `null` or `undefined` before calling a method on an object

**Are there any files to ignore?**

2021-07-01 21:09 UTC, nbbeeken requested changes
Thanks! yea, I agree catching and improving the error message would be good here

Slight message refactor suggestion so that its the same as the error message we have in 4.x

made NODE-3397 to track

2021-07-01 21:09 UTC, nbbeeken commented on lib/core/connection/connect.js
> +      return callback(new MongoError(`authMechanism '${credentials.mechanism}' not supported`));
```suggestion
      return callback(new MongoError(`No AuthProvider for ${credentials.mechanism} defined.`)); 
```

2021-07-01 22:00 UTC, vkarpov15 commented on lib/core/connection/connect.js
> +      return callback(new MongoError(`authMechanism '${credentials.mechanism}' not supported`));
Works for me :+1:

2021-07-02 14:29 UTC, nbbeeken approved these changes
LGTM

2021-07-02 14:48 UTC, emadum approved these changes

2021-07-02 15:18 UTC, merged