feat(NODE-3419): defined MongoRuntimeError children
mongodb/node-mongodb-native pull request #2893
Opened 2021-07-08 17:27 UTC by andymina

## Description
- Added class definitions of MongoRuntimeError children as seen in the second and third graph of [docs/errors.md](https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/errors.md).

**What changed?**
Classes added:
- MongoURIError
- MongoCompressionError
- MongoDecompressionError
- MongoTransactionError
- MongoExpiredSessionError
- MongoKerberosError
- MongoStreamError
- MongoChangeStreamError
- MongoGridFSStreamError
- MongoGridFSChunkError
- MongoResourceClosedError
- MongoServerClosedError
- MongoStreamClosedError
- MongoTopologyClosedError

2021-07-08 19:30 UTC, W-A-James approved these changes
LGTM 👍🏿

2021-07-09 13:17 UTC, emadum requested changes
I think this documentation would read better if we replaced the boilerplate `An error generated when an attempt is made to ...` to something more succinct like `Thrown when attempting to ...`. Could we also make the line length used for wrapping consistent across all the docs?

2021-07-09 13:17 UTC, emadum commented on src/error.ts
> + * An error generated when teh driver fails to decompress
```suggestion
 * An error generated when the driver fails to decompress
```

2021-07-09 13:17 UTC, emadum commented on src/error.ts
> + * An error generated when an attempt to access a resource
```suggestion
 * An error generated when an attempt is made to access a resource
```

2021-07-09 19:58 UTC, nbbeeken approved these changes
Seconded on Eric's comments, otherwise LGTM

2021-07-10 13:14 UTC, emadum approved these changes
LGTM 👍

2021-07-12 14:29 UTC, dariakp approved these changes
LGTM

2021-07-13 19:53 UTC, merged