fix(NODE-3727): add overloads for BulkOperationBase's execute function
mongodb/node-mongodb-native pull request #3018
Opened 2021-10-28 08:16 UTC by skrtheboss

### Description

Add overloads for BulkOperationBase's execute function.

#### What is changing?

This adds overloads to the execute function, to ensure void is returned if a callback is provided, 
and a promise is returned if no callback is specified.

##### Is there new documentation needed for these changes? No.

#### What is the motivation for this change?

Missing overloads.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2021-10-29 18:43 UTC, dariakp reviewed
Thank you for adding tests for this implementation, we'll full review the PR soon. Meanwhile, I created this ticket for tracking: https://jira.mongodb.org/browse/NODE-3727

2021-10-29 18:43 UTC, dariakp reviewed
Thank you for adding tests for this implementation, we'll fully review the PR soon. Meanwhile, I created this ticket for tracking: [NODE-3727](https://jira.mongodb.org/browse/NODE-3727 )

2021-11-02 20:02 UTC, dariakp requested changes

2021-11-02 20:05 UTC, nbbeeken approved these changes
LGTM

2021-11-02 20:05 UTC, dariakp approved these changes
Thanks again for your submission!

2021-11-02 20:11 UTC, merged