<docs>: Clarify that deprecation is a "feat" type commit
mongodb/node-mongodb-native pull request #3052
Opened 2021-11-19 19:23 UTC by ljhaywar

### Description

#### What is changing?

Update to the contributing guidelines to indicate that a feature deprecation is a "feat" commit type

##### Is there new documentation needed for these changes?

No

#### What is the motivation for this change?

I wasn't sure what commit type to use when I deprecated a feature

### Double check the following

- [ ] ~~Ran `npm run check:lint` script~~
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] ~~Changes are covered by tests~~
- [ ] ~~New TODOs have a related JIRA ticket~~

2021-11-22 13:33 UTC, durran commented
Changed base branch to main.

2021-11-22 13:34 UTC, durran requested changes
@ljhaywar Could you rebase again please - I changed the base branch to main so it shows up in the default repo but there are some conflicts now.

2021-11-30 14:45 UTC, ljhaywar commented
Thanks for catching that, Durran! I've rebased.

2021-12-02 20:09 UTC, nbbeeken approved these changes
I think this fell off the radar, seems ready to merge!

2021-12-03 15:45 UTC, durran approved these changes

2021-12-03 15:45 UTC, merged