Add let option to bulk write
mongodb/node-mongodb-native pull request #3160
Opened 2022-03-04 16:43 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-03-07 14:52 UTC, baileympearson commented
evergreen rebuild

2022-03-07 14:53 UTC, baileympearson commented
evergreen retry

2022-03-10 20:49 UTC, dariakp requested changes
Just a small suggestion, otherwise LGTM

2022-03-10 20:49 UTC, dariakp commented on test/tools/unified-spec-runner/operations.ts
> +  const operations = operation.arguments.requests;
You can do this a little bit more concisely like in some other operations here by doing:
`const { requests: operations, ...options } = operation.arguments;`

2022-03-10 21:58 UTC, dariakp approved these changes

2022-03-10 22:36 UTC, nbbeeken approved these changes

2022-03-11 07:12 UTC, durran approved these changes

2022-03-11 14:40 UTC, merged