fix(NODE-4074): ensure getTopology doesn't throw synchronously
mongodb/node-mongodb-native pull request #3172
Opened 2022-03-15 19:42 UTC by baileympearson

### Description

This PR is a re-do of the work done by <name> (original PR: https://github.com/mongodb/node-mongodb-native/pull/3170).  I messed up the rebase and accidentally removed all changes.

#### What is changing?

All uses of `getTopology` that are used in an asynchronous manner now catch any errors thrown and pass the error along to the appropriate callback.

##### Is there new documentation needed for these changes?

Nope! 

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2022-03-16 15:07 UTC, nbbeeken requested changes

2022-03-16 15:07 UTC, nbbeeken commented on test/integration/connection-monitoring-and-pooling/connection.test.js
> +        expect(err).to.match(/must be connected/);
Can we check for instanceof `MongoNotConnectedError` class instead, error messages are subject to change.

2022-03-16 15:07 UTC, nbbeeken commented on test/integration/connection-monitoring-and-pooling/connection.test.js
> +        await collection.insertOne({ a: 2 });
We need an expect.fail() below the insertOne to make sure the error doesn't disappear on us.

An alternative:
```ts
const error = await collection.insertOne({a:2}).catch(error => error)
expect(error).to.be.instanceOf(MongoNotConnectedError)
```
You can keep it all a oneliner and it catches both cases here, if it succeeds the instanceOf will fail, if it throws we get our error returned to us.

2022-03-16 15:07 UTC, nbbeeken commented on test/integration/connection-monitoring-and-pooling/connection.test.js
> +        await collection.insertOne({ a: 2 });
Same issue from other thread, need expect.fail or alternative approach.

2022-03-16 15:07 UTC, nbbeeken commented on src/utils.ts
>   * if the topology cannot be found.
Let's add an `@throws` to the tsdoc here, might help the next person catch themselves if more usage of the helper is needed in the future.

2022-03-16 19:48 UTC, nbbeeken approved these changes

2022-03-16 20:29 UTC, nbbeeken requested changes
Just noticed 😅  We've got some lint errors to sort out

2022-03-17 21:02 UTC, nbbeeken approved these changes

2022-03-21 15:59 UTC, robertsLando commented
Any news on this?

2022-03-21 18:27 UTC, dariakp commented on src/operations/execute_operation.ts
> +    try {
Let's run some perf tests as a sanity check to make sure we aren't incurring a perf hit with this added logic

2022-03-21 21:23 UTC, dariakp approved these changes

2022-03-21 21:23 UTC, merged

2022-04-05 07:17 UTC, robertsLando commented
Seems that there are still some collections methods that could throw:

https://github.com/mongodb/node-mongodb-native/blob/main/src/collection.ts#L762

https://github.com/mongodb/node-mongodb-native/blob/main/src/collection.ts#L1411

2022-04-05 13:28 UTC, baileympearson commented
Hey @robertsLando!  These methods can still throw.  However, they're actually synchronous methods so throwing is the expected behavior (any method that returns a cursor is synchronous because cursors are lazy and don't fetch data until they're consumed).

The other methods in this PR needed to be fixed because they took callbacks.  Previously, if we didn't catch the error and the user passed a callback, we could crash the user's process because we weren't propagating the error up the callback chain.

2022-04-05 14:09 UTC, robertsLando commented
Yeah I know that (I'm the user who opened the issue and PR for this). I just saw the new release today and when I tested it I got this issue. While I understand what you mean I don't think this behaviour is correct as it's not working as before, in my opinion the error should be thrown when `next` is called (like it was before). Wrapping every find with a try catch is much less user friendly

Before:
```js
collection.find({}).next( (err, doc) => {
// err contains the error connection is not opened
})
```

Now:
```js
try {
collection.find({}).next( (err, doc) => {
 		// never reached
})
} catch(error) {
 // error contains the error connection is not opened

}
```

2022-04-05 16:20 UTC, baileympearson commented
Just to clarify - you're saying that the behavior changed in v4.5.0?  I've tried in all versions 4.3.0 -> 4.5.0 and in all cases I see the error being caught in the `catch` block, not in the `next` function.

```typescript
import { MongoClient } from "mongodb";

async function run() {
  const client = new MongoClient(< uri >);

  const db = client.db('nodeTest');
  const collection = db.collection('nodeTest');

  try {
    collection.find({}).next(( )=> {
      console.log('caught error inside next');
    });
  } catch (err) {
    console.log('error caught in catch')
  }
}

run();
```

2022-04-06 06:34 UTC, robertsLando commented
> Just to clarify - you're saying that the behavior changed in v4.5.0

Nope this has changed in 4+ version but I didn't see it reported as breaking change. Also as you can see in my example the code looks a bit less user friendly