chore(NODE-4075): add docs generation workflow
mongodb/node-mongodb-native pull request #3189
Opened 2022-04-05 17:27 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-04-06 13:51 UTC, baileympearson commented
evergreen retry

2022-04-06 13:51 UTC, baileympearson commented
evergreen rebuild

2022-04-08 20:09 UTC, nbbeeken requested changes

2022-04-08 20:09 UTC, nbbeeken commented on .github/workflows/build_docs.yml
> +        npm run build:docs -- --yes
Can you break these up into each step and I think we can drop the version output? it should show up in the apt install bit.

2022-04-11 18:10 UTC, merged