feat(NODE-4185): Allow opting out of disk use
mongodb/node-mongodb-native pull request #3230
Opened 2022-05-03 13:15 UTC by lerouxb

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-05-03 13:32 UTC, addaleax submitted a review, later dismissed

2022-05-03 17:34 UTC, baileympearson commented
Hey @lerouxb and @addaleax - the Node team discussed this work yesterday during our triage.  The Node driver currently doesn't pass along a value for `allowDiskUse` if no value is specified from the user.  This means that drivers changes aren't necessary for this work, because we won't be overriding the new server default with the old default.  The only other work associated with this change sync the new spec tests, which due to a miscommunication and time zone differences, @kampofo completed this morning (see https://github.com/mongodb/node-mongodb-native/pull/3231).  Sorry for the duplicated effort here but we'll close this PR and use Kobby's since the work is completed there.

2022-05-03 18:00 UTC, addaleax commented
Talked with @baileympearson on Slack, it seems like https://github.com/mongodb/node-mongodb-native/pull/3231 makes this appear like something that’s already done, but in reality the tests there don’t test the builder API, only the options object API, so we do still want this :slightly_smiling_face:

2022-05-03 19:09 UTC, baileympearson commented
Yup.  We still want to make this change, but we should add tests for the new options.  I think the tests should go in `find_cursor_methods.js`.

As far as testing this option, we can use command monitoring on the MongoClient to ensure that the `find` commands contain the allowDiskUse option when they're sent to the database with the correct value.

2022-05-04 16:07 UTC, baileympearson requested changes

2022-05-04 16:07 UTC, baileympearson commented on src/cursor/find_cursor.ts
> +    // As of 6.0 the default is true. This allows users to get back to the old behaviour.
We should move this check to below the check for `sort`.  

Can we also add tests confirming that a MongoInvalidArgumentError is thrown if the user attempts to set allowDiskUse without a sort on their query?

2022-05-05 14:05 UTC, baileympearson approved these changes

2022-05-05 14:46 UTC, durran approved these changes

2022-05-05 17:13 UTC, merged