fix(NODE-4232): stream() also returns generic AsyncIterable
mongodb/node-mongodb-native pull request #3234
Opened 2022-05-05 15:10 UTC by qwelias

### Description

#### What is changing?
AbstractCursor#stream also returns `AsyncIterator<TSchema>`

##### Is there new documentation needed for these changes?
update autogenerated docs maybe

#### What is the motivation for this change?
need to carry the type when doing async iteration over stream() result

### Double check the following

- [x] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [x] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-05-05 20:27 UTC, durran requested changes
Hi @qwelias, would you also mind adding the type and a test to `ChangeStreamCursor` as well for consistency? (https://github.com/mongodb/node-mongodb-native/blob/main/src/change_stream.ts#L545). Thanks!

2022-05-05 21:40 UTC, durran requested changes
Also I believe we need a test to actually check that the iterator is valid in the for-await-of use case in the cursor type test:

```js
const cursor1 = collection.find();
const x = cursor1.stream();
for await (const doc of x) {
  expectType<{ age: number }>(doc);
}
```

2022-05-09 15:16 UTC, nbbeeken approved these changes
LGTM thanks!

2022-05-09 19:51 UTC, baileympearson approved these changes

2022-05-10 12:26 UTC, merged