refactor(NODE-4125): misc change stream improvements
mongodb/node-mongodb-native pull request #3284
Opened 2022-06-03 00:36 UTC by baileympearson

#### What is changing?

##### Is there new documentation needed for these changes?

No.

#### What is the motivation for this change?

As a part of NODE-4125, I made a couple of small refactors.  NODE-4125 isn't done, but I broke these changes into a separate PR.  I made 5 distinct changes:

1. added another overload for `.only` describe blocks to our mocha config
2. moved change stream cursor into its own file in the cursors subdirectory
3. added a doc comment to the `next<T>` function, explaining what the `blocking` parameter does
4. moved the `tryNext` function on the change stream to be grouped with the other iterator methods
5. created a custom readable that extends Readable instead of using the Readable constructor method the Node library provides

I think point 5 is probably the only change that will cause contention so I'm happy to revert if it we decide that's what we want to do.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2022-06-03 20:02 UTC, nbbeeken requested changes

2022-06-03 20:02 UTC, nbbeeken commented on src/cursor/abstract_cursor.ts
> + * @param callback - called when
cutoff?

2022-06-03 20:55 UTC, baileympearson commented on src/change_stream.ts
> +        if (err) return this._closeWithError(err);
Great catch - no it was not.  Another refactor I want to make is to break apart the logic for iterating the stream and iterating the cursor so stuff like this wouldn't happen.  But I don't want to do that until I have comprehensive test coverage for resumability (working on that in my actual ticket)

2022-06-10 14:32 UTC, baileympearson commented on src/cursor/abstract_cursor.ts
> + * @param callback - called when
yup

2022-06-10 15:14 UTC, baileympearson commented on global.d.ts
> +    interface ExclusiveSuiteFunction {
done

2022-06-10 15:32 UTC, baileympearson commented on src/cursor/change_stream_cursor.ts
> +import type { Document } from 'bson';
done

2022-06-10 15:32 UTC, baileympearson commented on src/cursor/change_stream_cursor.ts
> +  type ChangeStreamAggregateRawResult,
done

2022-06-10 15:33 UTC, baileympearson commented on src/cursor/abstract_cursor.ts
> +  private _needToClose = true; // NOTE: we must close the cursor if we never read from it, use `_construct` in future node versions
addressed

2022-06-10 17:54 UTC, nbbeeken approved these changes

2022-06-10 20:40 UTC, nbbeeken approved these changes

2022-06-10 20:41 UTC, merged