test(NODE-4264): add coverage for auto connecting operations
mongodb/node-mongodb-native pull request #3299
Opened 2022-06-24 20:55 UTC by nbbeeken

### Description

#### What is changing?

Using API extractor generate all the operations that could connect the mongo client automatically.

#### What is the motivation for this change?

Covering each operation checking that it performs auto connect.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2022-06-29 21:07 UTC, nbbeeken commented on test/integration/node-specific/auto_connect.test.ts
> +      // TODO: Ask bailey for help
@baileympearson

2022-06-29 21:08 UTC, nbbeeken commented on test/integration/node-specific/auto_connect.test.ts
> +  });
Let me unskip these now and we can assert the opposite that they DO throw if run first

2022-06-30 18:56 UTC, baileympearson requested changes

2022-07-01 17:41 UTC, baileympearson commented on test/integration/node-specific/auto_connect.test.ts
> +        .catch(error => (error instanceof MongoServerError ? null : error));
Making this comment more general because there are a number of occurrences on seemingly random methods.  Are these intended?

2022-07-01 18:02 UTC, nbbeeken commented on test/integration/node-specific/auto_connect.test.ts
> +        .catch(error => (error instanceof MongoServerError ? null : error));
I started handling this way b/c I thought it was important to make sure it was an error from the server, but I don't think its important to check that as long as the topology exist check passes. good catch!

2022-07-05 17:36 UTC, nbbeeken commented on src/gridfs/index.ts
> +            // TODO(NODE-XXX): This should be a subclass of server error
deleted per discussion. This is a driver side check per the spec

2022-07-05 18:00 UTC, baileympearson approved these changes

2022-07-06 14:48 UTC, durran submitted a review, later dismissed
LGTM

2022-07-06 15:11 UTC, dariakp requested changes

2022-07-06 15:11 UTC, dariakp commented on test/integration/node-specific/auto_connect.test.ts
> +      expect(client).to.not.have.property('topology'); // withSession won't connect, that's expected
I glanced through this PR and I don't have much to add, but I don't think we should make it a convention to use the `it` block for anything other than describing an action. The idea behind the test conventions is to make it easy to tell the intention from reading the actual spec printout. This comment here wouldn't show in the printout. We'd have Mongo Client Autoconnect class MongoClient #withSession()" which tells us nothing. If we're going for clarity, the #tag method names should be in the context or describe blocks and the `it` blocks should actually state the expectation.

2022-07-06 20:35 UTC, merged