test: unskip all key management tests
mongodb/node-mongodb-native pull request #3322
Opened 2022-07-13 20:49 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-07-15 09:33 UTC, addaleax submitted a review, later dismissed

2022-07-21 02:34 UTC, baileympearson commented on test/tools/unified-spec-runner/unified-utils.ts
> +          : 'requires mongodb >= 4.2 to run csfle tests';
Another fix to this logic - here's the actual spec https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#runonrequirement

The server must be >=4.2.0 AND csfle must be enabled for the driver.  For us, we rely on the configuration's `enabled` property to be consistent through all our tests.

2022-07-21 02:47 UTC, baileympearson commented on .evergreen/run-custom-csfle-tests.sh
> +CSFLE_GIT_REF=${CSFLE_GIT_REF:-b14d06000535e55be0c619e936972805cac24d37}
https://github.com/mongodb/libmongocrypt/commit/b14d06000535e55be0c619e936972805cac24d37 (latest mongodb-client-encryption release)

2022-07-21 02:47 UTC, baileympearson commented on test/tools/unified-spec-runner/operations.ts
> +  return clientEncryption.getKeys().toArray();
`getKeys` returns a cursor, missed in the initial implementation of these operations in the unified runner

2022-07-25 18:25 UTC, addaleax approved these changes
lgtm!

2022-07-25 19:31 UTC, nbbeeken approved these changes

2022-07-25 19:33 UTC, dariakp requested changes
Just an organizational question here - was this supposed to be linked to a different subtask? The ticket this is linked to has already been closed, so I'm kind of confused where this sits with respect to the parent ticket

2022-07-26 15:49 UTC, dariakp approved these changes

2022-07-26 17:40 UTC, merged