fix(update): correct `UpdateResult.upsertedId` type to include null
mongodb/node-mongodb-native pull request #3323
Opened 2022-07-16 16:51 UTC by vkarpov15

### Description

`upsertedId` can be `null`, but the types don't reflect this

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-07-20 01:12 UTC, vkarpov15 commented
I may be able to take a look at this later this week, but not 100%. Thanks for the feedback.

2023-04-10 18:02 UTC, dariakp requested changes

2023-04-10 18:02 UTC, dariakp commented on src/operations/update.ts
> +  upsertedId: ObjectId | null;
This doesn't account for [setOnInsert](https://www.mongodb.com/docs/v6.0/reference/operator/update/setOnInsert/#example)

2023-04-10 18:05 UTC, dariakp commented
Closing this in favor of NODE-5171

2023-04-10 18:05 UTC, closed without merging