fix(NODE-4425): webpack optional import of FLE issue
mongodb/node-mongodb-native pull request #3324
Opened 2022-07-18 18:58 UTC by nbbeeken

### Description

#### What is changing?

Move FLE require back into a try catch block.

#### What is the motivation for this change?

Webpack needs optional requires to be inside of a try catch. 

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-07-18 19:16 UTC, dariakp requested changes
Should we add a test for fle to `optional_require.test.js`?

2022-07-18 19:55 UTC, nbbeeken commented
> Should we add a test for fle to `optional_require.test.js`?

From slack, decided to follow up with this: https://jira.mongodb.org/browse/NODE-4442

2022-07-18 20:03 UTC, dariakp submitted a review, later dismissed

2022-07-19 15:19 UTC, dariakp requested changes
need to address lint failures

2022-07-19 21:21 UTC, dariakp approved these changes

2022-07-19 21:22 UTC, merged