chore: add 6.0 lb test
mongodb/node-mongodb-native pull request #3329
Opened 2022-07-20 18:01 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-07-20 20:11 UTC, nbbeeken requested changes

2022-07-20 20:11 UTC, nbbeeken commented on .evergreen/config.yml
> +  - name: test-load-balancer-6.0.0
Can we flip the name to align with the other test tasks? (also use load-balanced to match the topo type in the driver)
- `test-5.0-load-balanced`
- `test-6.0-load-balanced`
- `test-latest-load-balanced`

2022-07-26 19:20 UTC, nbbeeken approved these changes

2022-07-26 22:43 UTC, dariakp approved these changes

2022-07-26 22:58 UTC, merged