test: sync skipped StaleShardVersion change stream unifed tests
mongodb/node-mongodb-native pull request #3331
Opened 2022-07-25 17:09 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-07-27 12:02 UTC, durran requested changes
Verified this is passing: https://evergreen.mongodb.com/task_log_raw/mongo_node_driver_next_ubuntu_18.04_erbium_test_6.0_replica_set_patch_05e007b0b5ff98151c3ff972ee2f881b4203639e_62dece4d3066152bc52afacf_22_07_25_17_09_34/0?type=T#L882

Can we just fill out the PR description then please?

2022-07-27 15:20 UTC, baileympearson commented
Yes, good call 😅.  I filled out the PR description.

2022-07-28 11:30 UTC, durran submitted a review, later dismissed

2022-07-28 13:42 UTC, baileympearson commented
Rebased off of main to pull in the flakey load balancer test fix so CI can pass on this PR.

2022-07-28 17:30 UTC, durran approved these changes

2022-07-28 17:38 UTC, nbbeeken approved these changes

2022-07-28 18:09 UTC, dariakp approved these changes

2022-07-28 18:59 UTC, merged