test(NODE-4395): add csfle master && pinned commit tasks to CI
mongodb/node-mongodb-native pull request #3334
Opened 2022-07-26 17:42 UTC by baileympearson

### Description

#### What is changing?

A new task as been added to the custom dependency tests to test against libmongocrypt master.  The existing task was also renamed to indicate that it tests against a pinned commit, instead of the latest master.

2022-07-27 12:08 UTC, durran requested changes
I feel like this: https://github.com/mongodb/node-mongodb-native/blob/main/.evergreen/run-custom-csfle-tests.sh#L30 should maybe default back to master like before, so if we miss the variable in the future somewhere with new potential tasks we don't accidentally point at an old commit if we've bumped elsewhere. But I'm not too opinionated about it and am fine if it stays as is.

2022-07-28 11:29 UTC, durran approved these changes

2022-07-28 19:04 UTC, dariakp approved these changes

2022-07-28 19:08 UTC, dariakp requested changes
Quick question - I noticed both of the tasks that ran in the CI for this PR seem to have downloaded the same commit, is the variable currently set somewhere else, too, that's overriding master?

2022-07-28 19:52 UTC, dariakp approved these changes

2022-07-29 12:03 UTC, merged