fix(NODE-4467): Add back support for `oplogReplay` option as deprecated
mongodb/node-mongodb-native pull request #3337
Opened 2022-07-27 20:24 UTC by sampaiodiego

### Description
The option has been deprecated for MongoDB >=4.4 but should still be available to MongoDB <=4.2

#### What is changing?
Oplog tailing for MongoDB server <=4.2 can still use this flag in order to have a better performance.

##### Is there new documentation needed for these changes?
No

#### What is the motivation for this change?
The initial query to tail the oplog on huge MongoDB 4.2 servers was taking too long to complete.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2022-07-28 12:11 UTC, durran requested changes
Thanks @sampaiodiego for the PR! Could you add a unit test similar to the other operation constructor tests (example: https://github.com/mongodb/node-mongodb-native/blob/main/test/unit/operations/aggregate.test.js) so have a test to avoid another regression?

2022-07-28 15:11 UTC, sampaiodiego commented
sure thing @durran .. I've added a few tests, let me know if that's good enough.. thx

2022-07-29 12:28 UTC, durran approved these changes

2022-08-01 14:23 UTC, nbbeeken approved these changes

2022-08-01 18:31 UTC, merged