test(NODE-4422): use shared lib in prose tests
mongodb/node-mongodb-native pull request #3354
Opened 2022-08-11 18:03 UTC by durran

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-08-11 19:25 UTC, durran commented on .evergreen/generate_evergreen_tasks.js
> +[ '5.0', 'rapid', 'latest' ].forEach(version => {
These 3 cover the 5.x/6.x cases plus whatever current rapid is.

2022-08-11 19:26 UTC, durran commented on test/integration/client-side-encryption/client_side_encryption.prose.corpus.test.js
> +            extraOptions
All these tests now include `extraOptions.sharedCryptLibPath` when `CRYPT_SHARED_LIB_PATH` is in the env.

2022-08-11 19:27 UTC, durran commented on test/unit/operations/get_more.test.ts
> +      const server = new Server(
Unrelated to this ticket but this test was failing on main.

2022-08-11 19:29 UTC, durran commented on .evergreen/config.in.yml
> +          echo "CRYPT_SHARED_LIB_PATH: $CRYPT_SHARED_LIB_PATH"
It's not actually setting it here, just echoing the value.

2022-08-11 19:30 UTC, durran commented on .evergreen/prepare-crypt-shared-lib.sh
> -  exit 1
Not exiting here allows us to run the same script in evergreen for all csfle tests, so it continues running when server is less than 6.0 and the env var doesn't get set.

2022-08-12 09:31 UTC, jimmywarting commented
why don't you have issues enabled?

anyhow, wanted to report an issue with async iterators (cursors) being quite slow...

i found a way to make it faster using `cursor.forEach` and still `yield` all the values
i think the problem is b/c it's using a bunch of nextTick or promises or what not...

This is the slow version:
```js
const cursor = await table.aggregate(...)
for await (const doc of cursor) {
  // ... slow
}
// But i found that forEach was much faster...
table.aggregate(...).forEach()
```

logging the code of `cursor[Symbol.asyncIterator].toString()` showed me that it look something like this:
```js
function asyncIterator() {
  const cursor = this;

  return {
    next: function() {
      return Promise.resolve()
        .then(() => cursor.next())
        .then(value => {
          if (!value) {
            return cursor.close().then(() => ({ value, done: true }));
          }
          return { value, done: false };
        });
    }
  };
}
```
I bet all the slow part/bits are all the asynchronous promises that `.then()` makes that makes it slower? i don't know...

so i found a way to make it faster:
```js
// Turn a object that only has a forEach method into a async generator
async function* fasterAsyncGenerator(cursor) {
    const result = [];
    let done = false;
    let resolve = () => {};
    // When data arrives in chunks, then forEach will be called synchronous 
    // {batchSize} times and then wait for new chunks of data to arrive.
    cursor.forEach(doc => {
        result.push(doc);
        resolve();
    }, () => (done = true));

    while (!done || result.length) {
        // this while loop will be called (total of docs) / chunkSize
        await new Promise(rs => resolve = rs);
        yield * result.splice(0); // the length of result is chunkSize most often
    }
}
```
and using the code above as such:
```js
const cursor = await table.aggregate(...)
for await (const doc of fasterAsyncGenerator(cursor)) {
  // 
}
```
made the code faster. it went from 1.168s down to 680.719ms. (currently using mongodb: v3.6.3)

2022-08-12 13:26 UTC, baileympearson commented
Hi @jimmywarting - we use Jira to track bug issues and feature requests, not Github issues.  We have instructions for filing a bug report on our readme [here](https://github.com/mongodb/node-mongodb-native#bugs--feature-requests).  Going through our Jira ensures that we will see it during our weekly triage meetings.  Would you mind filing a bug report on Jira reporting this issue?  We would greatly appreciate it if you didn't comment on unrelated PRs with bug reports 🙂.  

This isn't a full answer, but your solution builds an array containing all results of cursor into memory.  One benefit of the async iterator approach or the forEach approach is that no more memory is consumed than is necessary.  Have you tried using `toArray()` instead?  That may give you the performance you're looking for:

```typescript
const resultArray = await table.aggregate(...).toArray()
for (const doc of resultArray) {
  // 
}
```

2022-08-12 19:38 UTC, baileympearson requested changes
We also run the csfle tests as a part of the general integration test task for each server/topology (it's run as a part of run-test.sh) for all servers >= 4.2.  We also need to ensure we're using the appropriate library for these tasks as well.

Additionally, we install mongodb-client-encryption for the bson-ext tests.  Can we check if the csfle tests run in the bson-ext task, and if they do can we update these as well?

2022-08-12 19:38 UTC, baileympearson commented on .evergreen/generate_evergreen_tasks.js
> +      name: `run-custom-csfle-tests-${version}-${ref == 'master' ? ref : 'pinned-commit'}`,
```suggestion
      name: `run-custom-csfle-tests-${version}-${ref === 'master' ? ref : 'pinned-commit'}`,
```

2022-08-15 17:13 UTC, durran commented
> We also run the csfle tests as a part of the general integration test task for each server/topology (it's run as a part of run-test.sh) for all servers >= 4.2. We also need to ensure we're using the appropriate library for these tasks as well.
> 
> Additionally, we install mongodb-client-encryption for the bson-ext tests. Can we check if the csfle tests run in the bson-ext task, and if they do can we update these as well?

It's now updated to run on everything now.

2022-08-15 18:02 UTC, baileympearson approved these changes
@durran One last comment - do you want to rebase?  It looks like the get_more unit test is still showing up in the diff.  Otherwise, looks good to me.  Thanks 😄

2022-08-16 14:07 UTC, baileympearson approved these changes

2022-08-16 14:07 UTC, merged