feat(NODE-4520): deprecate callback support and implement wrapper library
mongodb/node-mongodb-native pull request #3357
Opened 2022-08-15 15:17 UTC by nbbeeken

### Description

#### What is changing?

WIP

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

Backwards compat.

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-08-17 15:11 UTC, dariakp requested changes
Can you explain why the raw user options need to be exposed?

2022-08-17 18:56 UTC, baileympearson requested changes
Should this be a `feat` like Daria mentioned, and can we update the ticket description as well to reflect that you no longer are exporting the user options?

2022-08-17 19:20 UTC, baileympearson submitted a review, later dismissed

2022-08-17 20:15 UTC, dariakp approved these changes
Confirmed the use in the legacy client, here: https://github.com/mongodb-js/nodejs-mongodb-legacy/pull/1 so this should be ready to go

2022-08-18 03:14 UTC, durran commented on src/collection.ts
> +   * @param filter - The filter for the update operation.
Thanks for changing these to our spec language.

2022-08-18 03:14 UTC, durran approved these changes

2022-08-18 14:26 UTC, merged