feat(NODE-4540): add deprecation notice of callback support
mongodb/node-mongodb-native pull request #3360
Opened 2022-08-15 20:06 UTC by nbbeeken

### Description

#### What is changing?

Callback usage will now emit a deprecation warning once and instructions about how to migrate. 

Preview:
```txt
(node:55630) [MONGODB DRIVER] Warning: 
Callback support is deprecated and will be removed in the next major version.
If this impacts your usage of the driver there are few migration paths to consider:
  - You can start to using async/await syntax, which works with our driver today.
  - You can use .then/.catch at the end of any of our promise returning APIs and call you callback from within those.
  - You can install and import 'mongodb-legacy' a package that wraps all the async driver APIs and continues to provide the optional callback support.
You can read more about this here: LINK

(Use `node --trace-warnings ...` to show where the warning was created)
```

#### What is the motivation for this change?

Maintainable API, Sensible Error handling, consistent return values, less overloads, better type info.

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-08-16 19:43 UTC, dariakp requested changes

2022-08-16 19:43 UTC, dariakp commented on src/utils.ts
> +If this impacts your usage of the driver there are few migration paths to consider:
```suggestion
If this impacts your usage of the driver there are a few migration paths to consider:
```

2022-08-16 19:43 UTC, dariakp commented on src/utils.ts
> +  - You can start to using async/await syntax, which works with our driver today.
```suggestion
  - You can start using async/await syntax, which works with our driver today.
```

2022-08-16 19:43 UTC, dariakp commented on src/utils.ts
> +  - You can install and import 'mongodb-legacy' a package that wraps all the async driver APIs and continues to provide the optional callback support.
```suggestion
  - You can install and import 'mongodb-legacy': a package that wraps all the currently existing async driver APIs and continues to provide the optional callback support.
```

2022-08-16 19:43 UTC, dariakp commented on src/utils.ts
> +You can read more about this here: LINK\n`;
Leaving comment to make sure we remember to update this

2022-08-25 15:42 UTC, addaleax commented on src/utils.ts
> +    emitWarning: (message: string) => process.emitWarning(message, { code: MONGODB_WARNING_CODE })
Actually, one thing that is nice about the `Logger` API is that it is configurable on a per-MongoClient basis, not mutable global state. This PR isn't really changing that, but if there's an obvious way to make that happen, that would probably be quite a bit more useful for mongosh.

2022-08-29 17:19 UTC, closed without merging

2022-08-29 17:19 UTC, nbbeeken commented
Closing this in favor of a documentation only approach, will revisit runtime warning