fix(NODE-4735): fix change stream consecutive resumabilty
mongodb/node-mongodb-native pull request #3453
Opened 2022-10-20 18:38 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2022-10-25 17:25 UTC, baileympearson commented on src/change_stream.ts
> +      for (;;) {
```suggestion
      while(true) {
```

2022-10-25 17:25 UTC, baileympearson commented on src/change_stream.ts
> +      for (;;) {
```suggestion
      while(true) {
```

2022-10-25 17:25 UTC, baileympearson commented on src/change_stream.ts
> +      for (;;) {
```suggestion
      while(true) {
```

2022-10-26 15:42 UTC, dariakp commented on src/change_stream.ts
> +      for (;;) {
This is less obvious than a while true loop, so unless there's a particularly good reason to use this, I'd prefer the while loop (yes even with the lint warning, maybe even with a comment describing why this is definitely intentional)

2022-10-26 15:42 UTC, dariakp commented on test/integration/change-streams/change_stream.test.ts
> +          `supports consecutive resumes on error code ${code} ${error}`,
Just a note that these test additions will likely result in merge conflicts for https://github.com/mongodb/node-mongodb-native/pull/3454 and we should be extra careful in that PR, once it's rebased, that all these tests are pulled in

2022-10-26 16:00 UTC, dariakp requested changes

2022-10-26 16:00 UTC, dariakp commented on src/change_stream.ts
> +      // Change streams must resume indefinitely as long while each resume event succeeds.
Not sure the best way to fix "as long while", but it doesn't work semantically at the moment

2022-10-26 16:04 UTC, dariakp approved these changes

2022-10-26 16:10 UTC, nbbeeken approved these changes
LGTM

2022-10-26 18:17 UTC, merged