ci: pull in misc CI fixes for the 4x branch (#3536)
mongodb/node-mongodb-native pull request #3539
Opened 2023-01-24 18:16 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-01-25 14:51 UTC, durran requested changes
I think we need to change the FLE tests to not run on `LOWEST_LTS` as Node 12 does not support importing 'fs/promises'

2023-01-25 15:35 UTC, baileympearson commented
@durran Instead of bumping the node version, I changed the import.  We bumped to Node14 as a part of dropping support for Node12, which won't be a part of the 4.x branch.

2023-01-25 18:33 UTC, durran commented
> @durran Instead of bumping the node version, I changed the import. We bumped to Node14 as a part of dropping support for Node12, which won't be a part of the 4.x branch.

Better solution. Thanks!

2023-01-25 19:38 UTC, durran approved these changes

2023-01-26 15:27 UTC, nbbeeken approved these changes

2023-01-26 15:35 UTC, merged