test(WRITING-11435): test lambda function
mongodb/node-mongodb-native pull request #3569
Opened 2023-02-14 20:45 UTC by durran

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-04-06 17:44 UTC, durran commented on test/lambda/events/event.json
> +{
This is auto-generated and nothing read in the actual function from it.

2023-04-14 12:14 UTC, W-A-James requested changes

2023-04-14 12:26 UTC, durran commented on .evergreen/run-deployed-lambda-aws-tests.sh
> +#!/bin/bash
It looks like the AWS token expires in some cases before the script finishes: "The security token included in the request is expired". I'll get together with the build team and see if we can extend the expiration time.

2023-04-14 12:47 UTC, durran commented on .evergreen/run-deployed-lambda-aws-tests.sh
> +. ${DRIVERS_TOOLS}/.evergreen/run-deployed-lambda-aws-tests.sh
I've updated the script in tools to ensure that the entire script will run, ensuring the cluster always gets deleted: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/296

2023-04-19 12:43 UTC, durran commented on .evergreen/run-deployed-lambda-aws-tests.sh
> +. ${DRIVERS_TOOLS}/.evergreen/run-deployed-lambda-aws-tests.sh
That script is now merged, I've updated the PR to point back at tools master.

2023-05-01 17:14 UTC, W-A-James approved these changes

2023-05-01 17:15 UTC, merged