ci(no-story): ignore curl 92 errors when downloading node
mongodb/node-mongodb-native pull request #3603
Opened 2023-03-16 18:07 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-03-16 18:27 UTC, nbbeeken requested changes

2023-03-16 18:27 UTC, nbbeeken commented on .evergreen/install-dependencies.sh
> +if [ $code -ne 0 ] && [ $code -ne 92 ]; then echo "non-zero or 92 exit code while downloading NodeJS $code"; fi
```suggestion
if [[ $? -ne 0 && $? -ne 92 ]]; then echo "neither zero nor 92 exit code while downloading Node.js: got $code"; fi
```

2023-03-16 18:31 UTC, nbbeeken requested changes

2023-03-16 18:31 UTC, nbbeeken commented on .evergreen/install-dependencies.sh
> +if [[ $? -ne 0 && $? -ne 92 ]]; then echo "neither zero nor 92 exit code while downloading Node.js: got $code"; fi
```suggestion
if [[ $? -ne 0 && $? -ne 92 ]]; then echo "neither zero nor 92 exit code while downloading Node.js: got $?"; fi
```

2023-03-16 19:37 UTC, durran commented
Doesn't seem like even code 92 will work.

2023-03-17 18:39 UTC, nbbeeken commented
The purple storm has subsided 🟣⛈️

2023-03-17 18:39 UTC, closed without merging