feat(NODE-4795): deprecate addUser helper
mongodb/node-mongodb-native pull request #3624
Opened 2023-04-04 11:39 UTC by durran

### Description

Deprecates the addUser helper.

#### What is changing?
- Deprecates the addUser helper along with the associated options.

##### Is there new documentation needed for these changes?

None

#### What is the motivation for this change?

NODE-4795

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-04-05 08:37 UTC, durran commented
> We also need to deprecate the db#addUser helper method

Done.

2023-04-05 13:11 UTC, W-A-James approved these changes

2023-04-05 14:37 UTC, nbbeeken requested changes

2023-04-06 09:02 UTC, durran commented on src/admin.ts
> +   * @deprecated Use the createUser command directly instead.
Added here and on db.

2023-04-06 14:32 UTC, nbbeeken approved these changes

2023-04-06 17:54 UTC, W-A-James approved these changes

2023-04-06 17:54 UTC, merged