fix(NODE-5201): prevent warning when default value for deprecation option is used
mongodb/node-mongodb-native pull request #3646
Opened 2023-04-17 17:04 UTC by baileympearson

### Description

#### What is changing?

- Default options are no longer collected as a part of the `allOptions` map.  Since `allOptions` no longer contains defaults, it is now named `providedOptions`
- deprecation warnings are emitted inside `parseOptions`, not `setOption`, and are only emitted for non-default values

##### Is there new documentation needed for these changes?

No.

#### What is the motivation for this change?

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2023-04-17 18:20 UTC, nbbeeken requested changes

2023-04-17 18:20 UTC, nbbeeken commented on src/connection_string.ts
> +    allProvidedOptions.set(key, values);
Consider tracking source, feel free to resolve

2023-04-17 18:39 UTC, baileympearson commented on test/unit/mongo_client.test.js
> +      expect(clientViaUri.options).to.have.property('compressors').deep.equal(['zlib', 'snappy']);
Can you elaborate on this comment?  I'm not sure I understand the concern here - it seems like it's working as designed? 

- Options parsing constructs the options object that our driver uses.  If we fix a bug in options parsing related to compressors, and that will also affect the handshake but that's expected.
- We have tests to ensure that we don't break options parsing

Is there something different you're concerned with?

2023-04-17 19:07 UTC, nbbeeken commented on test/unit/mongo_client.test.js
> +      expect(clientViaUri.options).to.have.property('compressors').deep.equal(['zlib', 'snappy']);
We are fixing the fact that 'none' makes its way down to the handshake construction and gets sent to the server. I feel like we could add a catch to make sure that 'none' doesn't get reintroduced to the handshake. If its reasonable, which I think with the recent handshake tests that came with faas we have a framework to work with

2023-04-17 19:25 UTC, baileympearson commented on test/unit/mongo_client.test.js
> +      expect(clientViaUri.options).to.have.property('compressors').deep.equal(['zlib', 'snappy']);
are you looking for a test like:

```typescript
context('when compressors are set on the client options, () => {
  it('does not include `none` as an option on the handshake', () => .. );
});
```

2023-04-17 19:46 UTC, baileympearson commented on test/unit/mongo_client.test.js
> +      expect(clientViaUri.options).to.have.property('compressors').deep.equal(['zlib', 'snappy']);
How is that different than the existing tests?

2023-04-17 19:58 UTC, nbbeeken commented on test/unit/mongo_client.test.js
> +      expect(clientViaUri.options).to.have.property('compressors').deep.equal(['zlib', 'snappy']);
We don't have coverage for the handshake just options parsing, demonstrated by the fact that this change didn't fail anything

2023-04-17 20:45 UTC, nbbeeken approved these changes

2023-04-18 14:21 UTC, durran approved these changes

2023-04-18 14:51 UTC, merged