ci(NODE-5269): Add Node 20 to driver ci
mongodb/node-mongodb-native pull request #3664
Opened 2023-05-09 20:14 UTC by W-A-James

### Description

#### What is changing?

- Update `.evergreen/ci_matrix_constants.js` to include Node 20 and regenerate `.evergreen/config.yml`
- Update Github "Check Dependencies" action to use Node 20
- Refactor CI scripts and config to make use of `NODE_LTS_VERSION` rather than `NODE_LTS_NAME` to fix issue when trying to fetch Node 20

##### Is there new documentation needed for these changes?

No

#### What is the motivation for this change?

Ensure that the driver and its extensions are compatible with the latest officially released Node.js version.

### Double check the following

- [X] Ran `npm run check:lint` script
- [X] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [X] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [X] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-05-10 19:32 UTC, W-A-James commented on .evergreen/install-dependencies.sh
> +  node_index_major_version=$(echo $node_index_version | sed -E 's/^v([0-9]+).*$/\1/')
This sed invocation extracts the major version

2023-05-12 15:41 UTC, durran requested changes

2023-05-12 15:41 UTC, durran commented on .evergreen/run-kerberos-tests.sh
> +if [ "$NODE_LTS_VERSION" != "latest" ] || [ $NODE_LTS_VERSION -lt 20 ]; then
This will attempt to install 1.1.7 because `"20" != "latest"` - the kerberos tests then fail.

2023-05-12 15:49 UTC, durran commented on .evergreen/run-kerberos-tests.sh
> +if [ "$NODE_LTS_VERSION" != "latest" ] || [ $NODE_LTS_VERSION -lt 20 ]; then
Link to failures: https://evergreen.mongodb.com/task_log_raw/mongo_node_driver_next_rhel80_large_Node20_test_auth_kerberos_patch_ccf555d069f3bd0eb7e7b2cca0d5ecdc7d571332_645e43889ccd4e4552dfeca8_23_05_12_13_47_52/0?type=T#L189

2023-05-17 17:07 UTC, nbbeeken approved these changes
LGTM, logging the flakes and I'll merge

And we have: https://jira.mongodb.org/browse/NODE-5293 for the windows node14 issues

2023-05-17 17:49 UTC, merged