fix(Node-5272): backport ecc collection fix
mongodb/node-mongodb-native pull request #3678
Opened 2023-05-19 20:37 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-05-23 14:42 UTC, nbbeeken requested changes

2023-05-23 14:42 UTC, nbbeeken commented on src/operations/create_collection.ts
> +        if (server.description.maxWireVersion < MIN_SUPPORTED_QE_WIRE_VERSION) {
Daria had a question about whether this was necessary

2023-05-24 15:53 UTC, nbbeeken commented on src/operations/create_collection.ts
> +        if (server.description.maxWireVersion < MIN_SUPPORTED_QE_WIRE_VERSION) {
@baileympearson bump

2023-05-24 18:43 UTC, nbbeeken approved these changes

2023-05-24 18:48 UTC, nbbeeken commented
@baileympearson Is "fix" correct here? asking because the original PR was a feat

2023-05-24 19:15 UTC, baileympearson commented
I think so - why was the original PR a feat?  

- QE is experimental, so the breakage is okay
- this fixes a bug with QE and 7.0 servers, where we'd create extra unnecessary collections

2023-05-24 20:41 UTC, merged