feat(NODE-5319): mark search index api public
mongodb/node-mongodb-native pull request #3741
Opened 2023-06-22 22:49 UTC by baileympearson

### Description

#### What is changing?

The search index API is marked public. 

Also, @lerouxb noticed that the definition for `SearchIndexModel` was incorrect, although the code path (and our unified tests) do assert on the correct value at runtime.  This PR fixes the type.

##### Is there new documentation needed for these changes?

Yes, docsp ticket.

#### What is the motivation for this change?

### Release Highlight

### Programmatic management of search indexes

This PR adds support for managing search indexes (creating, updating, deleting and listing indexes).  The new methods are available on the `Collection` class.

```typescript
const indexes = await collection.listSearchIndexes().toArray(); // produces an array of search indexes
await collection.createSearchIndex({ name: 'my-index', definition: < index definition > } ); 
await collection.updateSearchIndex('my-index', < new definition >);
await collection.dropSearchIndex('my-index');
```

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-06-23 08:59 UTC, lerouxb commented on src/operations/search_indexes/create.ts
> +  definition: Document;
👍

2023-06-23 08:59 UTC, lerouxb approved these changes

2023-06-23 13:49 UTC, durran requested changes
Was the test changes commit intended to be part of this? Could we just limit it to the API changes and move that commit to a new branch for the next steps?

2023-06-23 14:08 UTC, baileympearson commented
@durran That was unintentional - somehow I had an extra commit from my search indexes work on main.  I've rebased it away now

2023-06-26 13:50 UTC, durran approved these changes

2023-06-26 14:23 UTC, merged