feat(NODE-4961)!: remove command result from commit and abort transaction APIs
mongodb/node-mongodb-native pull request #3784
Opened 2023-07-25 17:50 UTC by nbbeeken

### Description

#### What is changing?

- commit & abort transaction properly return void
- added a regression test

##### Is there new documentation needed for these changes?

The typescript has been updated.

#### What is the motivation for this change?

See notes

### Release Highlight

### `session.commitTransaction()` and `session.abortTransaction()` return void

Each of these methods erroneously returned server command results that can be different depending on server version or type the driver is connected to. These methods return a promise that if resolved means the command (aborting or commiting) sucessfully completed and rejects otherwise. Viewing command responses is possible through the [command monitoring APIs](https://www.mongodb.com/docs/drivers/node/upcoming/fundamentals/monitoring/command-monitoring/) on the MongoClient.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2023-07-25 18:15 UTC, nbbeeken commented
Needs test fixes from https://github.com/mongodb/node-mongodb-native/pull/3783, Otherwise ready for review.

2023-07-26 16:50 UTC, nbbeeken commented
I put fixes to the tests in this PR, they assert void return values for `withTransaction` which will change to the value of the result of the executor in the other PR. Which ever lands first can easily merge and use the correct assertions.

2023-07-28 19:29 UTC, baileympearson requested changes
There's a testing note in the ticket:

- Regression test

Do we have any tests that confirm these APIs return `void` (type or integration)?

2023-07-28 20:55 UTC, baileympearson approved these changes

2023-07-31 11:02 UTC, durran approved these changes

2023-07-31 15:09 UTC, merged