feat(NODE-3568)!: switch default
mongodb/node-mongodb-native pull request #3786
Opened 2023-07-26 14:59 UTC by W-A-James

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-08-01 12:32 UTC, durran requested changes
test/types/community/collection/findX.test-d.ts has some type tests to uncomment as part of this ticket. Also I expect those existing tests in that file to be failing, but they are not as the type definitions for `findOneAndUpdate`, `findOneAndDelete`, and `findOneAndReplace` are still typed as returning a `ModifyResult` when no options are passed or an options object without `includeResultMetadata` is provided - so those are incorrect with the new default.

2023-08-01 12:32 UTC, durran commented on src/client-side-encryption/clientEncryption.js
> +        { writeConcern: { w: 'majority' }, returnDocument: 'before', includeResultMetadata:true }
```suggestion
        { writeConcern: { w: 'majority' }, returnDocument: 'before', includeResultMetadata: true }
```

2023-08-01 12:32 UTC, durran commented on test/integration/crud/find.test.js
> +  it('shouldCorrectlyFindOneAndUpdateDocumentAndReturnSelectedFieldsOnly', {
```suggestion
  it('returns selected fields only for findOneAndUpdate', {
```

2023-08-01 12:32 UTC, durran commented on test/integration/node-specific/operation_examples.test.ts
> +      return client.connect().then(function(client) {
I feel that while we are reformatting here, we should probably:

1. Make this entire sequence use async/await
2. Fix the calls to `rename()` - it's an async function and its second argument is an options object, and does not take a callback so the signature is wrong in these tests.

2023-08-02 11:45 UTC, durran requested changes
Looking good, just a few minor suggestions. (I think the schema helpers type tests should just use the default). There may some linting fixes needed with my change suggestions.

2023-08-02 11:45 UTC, durran commented on test/types/community/collection/findX.test-d.ts
>  // Passing no options will return the modify result.
```suggestion
// Passing no options will return the deleted document.
```

2023-08-02 11:45 UTC, durran commented on test/types/community/collection/findX.test-d.ts
>  // Passing empty options will return the modify result.
```suggestion
// Passing empty options will return the deleted document.
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  (await typeTestCollection.findOneAndDelete({ a: 1 }, { includeResultMetadata: true })).value
```suggestion
  await typeTestCollection.findOneAndDelete({ a: 1 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  (await interfaceTestCollection.findOneAndDelete({ a: 1 }, { includeResultMetadata: true })).value
```suggestion
  await interfaceTestCollection.findOneAndDelete({ a: 1 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +    .value
```suggestion
  await typeTestCollection.findOneAndReplace({ a: 1 }, { a: 5 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  ).value
```suggestion
  await interfaceTestCollection.findOneAndUpdate({ a: 1 },{ a: 5 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  (await typeNumberTestCollection.findOneAndDelete({ a: 1 }, { includeResultMetadata: true })).value
```suggestion
  await typeNumberTestCollection.findOneAndDelete({ a: 1 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +    .value
```suggestion
  await interfaceNumberTestCollection.findOneAndDelete({ a: 1 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  ).value
```suggestion
  await typeNumberTestCollection.findOneAndReplace({ a: 1 }, { a: 5 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  ).value
```suggestion
  await interfaceNumberTestCollection.findOneAndReplace({ a: 1 }, { a: 5 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  ).value
```suggestion
  await typeNumberTestCollection.findOneAndUpdate({ a: 1 }, { a: 5 })
```

2023-08-02 11:45 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  ).value
```suggestion
  await interfaceNumberTestCollection.findOneAndUpdate({ a: 1 }, { a: 5 })
```

2023-08-02 14:47 UTC, nbbeeken commented on src/client-side-encryption/clientEncryption.js
> +        includeResultMetadata: true
Instead of setting the opposite of the default, any reason we shouldn't change `const { value } =` to `const value =` here?

2023-08-03 11:20 UTC, durran requested changes

2023-08-03 11:20 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +  ).value
```suggestion
    await interfaceTestCollection.findOneAndReplace({ a: 1 }, { a: 5 })
```

2023-08-03 11:20 UTC, durran commented on test/types/schema_helpers.test-d.ts
> +    .value
```suggestion
  await typeTestCollection.findOneAndUpdate({ a: 1 }, { a: 5 })
```

2023-08-03 14:30 UTC, durran submitted a review, later dismissed

2023-08-03 15:47 UTC, nbbeeken submitted a review, later dismissed

2023-08-04 12:42 UTC, durran commented
@W-A-James Can you fix the conflicts then I'll merge. Thanks!

2023-08-04 21:39 UTC, merged