feat(NODE-3989)!: only accept true and false for boolean options
mongodb/node-mongodb-native pull request #3791
Opened 2023-08-02 17:52 UTC by W-A-James

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-08-03 11:30 UTC, durran requested changes

2023-08-03 11:30 UTC, durran commented on test/unit/assorted/uri_options.spec.test.ts
> +    // Skipped because we now only accept true/false for boolean options
Maybe nice to note around here that the URI options spec expects warnings currently for invalid options and the Node driver throws.

2023-08-03 11:30 UTC, durran commented on test/unit/connection_string.test.ts
> +        }
```suggestion
        if (expectation === 'error') {
            it('throws MongoParseError', function () {
              expect(() => {
                parseOptions(connString);
              }).to.throw(MongoParseError);
            });
        } else {
            it(`parses as ${expectation}`, function () {
              const options = parseOptions(connString);
              expect(options).to.have.property('retryWrites', expectation);
            });
        }
```

I think as there are only 2 cases here `if...else` makes a bit more sense and is 1 less line of code.

2023-08-03 15:36 UTC, durran commented on test/unit/connection_string.test.ts
> +            it('throws MongoParseError', function () {
Think there's lint errors here now.

2023-08-03 15:37 UTC, durran requested changes
Lint errors.

2023-08-04 12:41 UTC, durran approved these changes

2023-08-04 17:21 UTC, nbbeeken approved these changes

2023-08-04 20:27 UTC, merged