chore(NODE-5446): update driver v6 deps
mongodb/node-mongodb-native pull request #3801
Opened 2023-08-08 18:00 UTC by W-A-James

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-08-10 15:09 UTC, baileympearson requested changes
question: how come we decided to disable `ban-types` in most of our lint configurations?

2023-08-10 15:09 UTC, baileympearson commented on package.json
>      "eslint-plugin-prettier": "^4.2.1",
did we decide not to bump gcp-metadata?

2023-08-15 19:08 UTC, W-A-James commented
@baileympearson re disabling ban-types, when updating the eslint and associated dev dependencies, we start getting the following lint failures

```
/home/wajames/node_driver/src/operations/operation.ts
  20:47  error  Don't use `Function` as a type. The `Function` type accepts any function-like value.
It provides no type safety when calling the function, which can be a common source of bugs.
It also accepts things like class declarations, which will throw at runtime as they will not be called with `new`.
If you are expecting the function to accept certain arguments, you should explicitly define the function shape  @typescript-eslint/ban-types

/home/wajames/node_driver/test/types/basic_schema.test-d.ts
  59:14  error  Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
- If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead  @typescript-eslint/ban-types

/home/wajames/node_driver/test/types/community/changes_from_36.test-d.ts
  16:15  error  Don't use `Function` as a type. The `Function` type accepts any function-like value.
It provides no type safety when calling the function, which can be a common source of bugs.
It also accepts things like class declarations, which will throw at runtime as they will not be called with `new`.
If you are expecting the function to accept certain arguments, you should explicitly define the function shape                                  @typescript-eslint/ban-types
  24:15  error  Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
- If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead  @typescript-eslint/ban-types

X 4 problems (4 errors, 0 warnings)
```

I wasn't sure if we wanted to address those here with code changes, so I disabled that rule, which in retrospect might have been a reach too far. I can disable the rule on a per-line basis and file a follow-up ticket.

2023-08-15 19:16 UTC, nbbeeken requested changes

2023-08-15 19:16 UTC, nbbeeken commented on .eslintrc.json
> +        "@typescript-eslint/ban-types": "off",
Let's fix the one violation in src: we can replace OperationConstructor with:
```ts
 { new (...args: any[]): any }
```

2023-08-15 19:56 UTC, nbbeeken approved these changes

2023-08-16 01:03 UTC, baileympearson approved these changes

2023-08-16 14:52 UTC, merged