fix(NODE-5477): set AWS region from environment variable for STSClient
mongodb/node-mongodb-native pull request #3831
Opened 2023-08-21 16:21 UTC by nbbeeken

### Description

#### What is changing?

- Adding detection for `AWS_STS_REGIONAL_ENDPOINTS` and `AWS_REGION` environment variables and setting the corresponding `fromNodeProviderChain` options.
- `LEGACY_REGIONS` is created from this: https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html documentation
- The driver will only set region options if BOTH environment variables are present, this is so that the driver does not encode a default setting for `AWS_STS_REGIONAL_ENDPOINTS`.

##### Is there new documentation needed for these changes?

Yes. Will file a docs ticket.

#### What is the motivation for this change?

AWS reccomends setting your STS region to be as close to your app as possible to reduce latency but currently the JS SDK does not use the common AWS region environment variables, and the setting must be controlled programatically.

Tracking issue here: https://github.com/aws/aws-sdk-js-v3/issues/5105

### Release Highlight

### **TODO needs clean up** 

- Adding detection for `AWS_STS_REGIONAL_ENDPOINTS` and `AWS_REGION` environment variables and setting the corresponding `fromNodeProviderChain` options.
- `LEGACY_REGIONS` is created from this: https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html documentation
- The driver will only set region options if BOTH environment variables are present, this is so that the driver does not encode a default setting for `AWS_STS_REGIONAL_ENDPOINTS`.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Release notes are filled out
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2023-08-21 18:55 UTC, nbbeeken commented on test/integration/auth/mongodb_aws.test.ts
> +          };
Ideally, we can find another mechanism to monitor the actual destination of the http request to complete the "integration" test.

2023-08-21 18:55 UTC, nbbeeken commented
Looking at the tests on this task:

[aws-6.0-auth-test-run-aws-auth-test-AssumeRoleWithWebIdentity-with-AWS_ROLE_SESSION_NAME-set](https://spruce.mongodb.com/task/mongo_node_driver_next_ubuntu1804_test_mongodb_aws_aws_6.0_auth_test_run_aws_auth_test_AssumeRoleWithWebIdentity_with_AWS_ROLE_SESSION_NAME_set_patch_a7ffdf5aca888d87dc5c8d9661891a6ca3121c36_64e3ac8fc9ec44e563bb571c_23_08_21_18_27_27?execution=0&sortBy=STATUS&sortDir=ASC)

2023-08-21 19:01 UTC, nbbeeken commented on src/cmap/auth/mongodb_aws.ts
> +  static credentialProvider: ReturnType<typeof getAwsCredentialProvider> | null = null;
This serves two purposes, 1. we usually cache our lazy imports so we don't call require more than once, 2. I can now access the SDK this auth code uses for testing purposes

Packages (this includes the driver!) that compile with typescript have all the properties on their `module.exports` defined as non-configurable getters. While this emulates ES Module live binding and immutability, it makes sinon spying impossible.

2023-08-22 19:16 UTC, W-A-James reviewed
Apart from the one question on the test file (which I won't block on), LGTM

2023-08-23 14:18 UTC, nbbeeken commented on test/integration/auth/mongodb_aws.test.ts
> +        };
It can be, I'll fix this

2023-08-24 15:21 UTC, durran requested changes

2023-08-24 15:21 UTC, durran commented on test/integration/auth/mongodb_aws.test.ts
> +        title: 'uses the region from the environment',
Should this be "uses the default region" ?

2023-08-28 13:49 UTC, W-A-James approved these changes

2023-08-29 19:47 UTC, merged