test(NODE-5606): use npm 9 on eol node versions
mongodb/node-mongodb-native pull request #3858
Opened 2023-09-01 19:21 UTC by durran

### Description

Fixes Node 16 failures with npm 10.

#### What is changing?

- Installs npm@9 when on Node 16 or lower.

##### Is there new documentation needed for these changes?

None

#### What is the motivation for this change?

NODE-5606

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-09-05 14:05 UTC, W-A-James requested changes

2023-09-07 17:06 UTC, durran commented on .evergreen/install-dependencies.sh
> +  if [[ $NODE_LTS_VERSION -lt $NODE_LOWEST_LTS ]]; then
Updated to parameterize NPM_VERSION now.

2023-09-07 19:04 UTC, W-A-James commented
Note that test failures are either a result of server changes to how explain documents are returned or known flaky tests

2023-09-07 19:04 UTC, W-A-James approved these changes

2023-09-07 20:12 UTC, merged