test(NODE-5619): use npm 9 on eol node versions (#3858)
mongodb/node-mongodb-native pull request #3861
Opened 2023-09-07 21:13 UTC by durran

### Description

Fixes Node 16 failures with npm 10.

#### What is changing?

- Installs npm@9 when on Node 16 or lower.

##### Is there new documentation needed for these changes?

None

#### What is the motivation for this change?

NOE-5619

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-09-08 13:58 UTC, nbbeeken reviewed
Kicked off node 14 and 16 tests

2023-09-08 14:21 UTC, nbbeeken requested changes

2023-09-08 14:21 UTC, nbbeeken commented on .evergreen/generate_evergreen_tasks.js
> +    const expansions = { NODE_LTS_VERSION, NPM_VERSION: NODE_LTS_VERSION === 16 ? 9 : 'latest' };
```suggestion
    const expansions = { NODE_LTS_VERSION, NPM_VERSION: NODE_LTS_VERSION <= 16 ? 9 : 'latest' };
```

Node 16 is fixed but we still test node 14 on 5.x, we're going to run into the same issue on the 4.x branch with node 12.

2023-09-11 16:16 UTC, nbbeeken approved these changes

2023-09-11 16:20 UTC, baileympearson approved these changes

2023-09-11 16:21 UTC, merged