docs: remove find-and-modify warning about defaults
mongodb/node-mongodb-native pull request #3995
Opened 2024-02-14 17:38 UTC by I3uckwheat

### Description

#### What is changing?

The previous version of the documentation (5.x) also had the lines that are removed in this commit. However, after testing and verifying, the default behavior is as-if the property "includeResultMetadata" was set to false.

##### Is there new documentation needed for these changes?

The change is documentation 

#### What is the motivation for this change?

Incorrect documentation 

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-02-19 09:39 UTC, durran approved these changes

2024-02-19 09:47 UTC, durran requested changes

2024-02-19 09:47 UTC, durran commented on src/operations/find_and_modify.ts
>     * Return the ModifyResult instead of the modified document. Defaults to true
```suggestion
   * Return the ModifyResult instead of the modified document. Defaults to false
```

2024-02-19 09:47 UTC, durran commented on src/operations/find_and_modify.ts
>     * Return the ModifyResult instead of the modified document. Defaults to true
```suggestion
   * Return the ModifyResult instead of the modified document. Defaults to false
```

2024-02-19 15:26 UTC, durran approved these changes

2024-02-19 16:01 UTC, merged

2024-02-26 16:06 UTC, I3uckwheat commented
Oh shoot, got confused. Thank you for fixing and merging!