feat(NODE-6008): deprecate CloseOptions interface
mongodb/node-mongodb-native pull request #4030
Opened 2024-03-08 21:19 UTC by W-A-James

### Description

#### What is changing?
* Deprecated `CloseOptions` interface

##### Is there new documentation needed for these changes?
No

#### What is the motivation for this change?
NODE-6008

### Release Highlight

### Deprecated unused `CloseOptions` interface

The public `CloseOptions` interface has been deprecated as it was originally meant for internal use in the driver and is now no longer used and will be removed in the next major release.

### Double check the following

- [X] Ran `npm run check:lint` script
- [X] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [X] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-03-08 21:41 UTC, baileympearson commented
@W-A-James Is the base branch for this PR correct?  (CI didn't run because it's not pointing to `main`)

2024-03-08 21:41 UTC, aditi-khare-mongoDB reviewed
code changes are minimal and LGTM, but do we know what's going on with the Ci alias?

2024-03-08 21:52 UTC, baileympearson commented
evergreen retry

2024-03-08 22:52 UTC, W-A-James commented
> @W-A-James Is the base branch for this PR correct? (CI didn't run because it's not pointing to `main`)

I didn't want to mark this as internal until we actually stop using it (once NODE-5915 is merged), so I pointed it at the branch with the changes that remove its usages.

2024-03-11 18:01 UTC, aditi-khare-mongoDB submitted a review, later dismissed

2024-03-11 18:03 UTC, nbbeeken requested changes

2024-03-11 18:03 UTC, nbbeeken commented on src/cmap/connection_pool.ts
> + * in the driver */
```suggestion
/** 
 * @public
 * @deprecated This interface is deprecated and will be removed in a future release as it is not used
 * in the driver 
 */
```

2024-03-11 18:09 UTC, aditi-khare-mongoDB approved these changes

2024-03-11 18:09 UTC, nbbeeken submitted a review, later dismissed

2024-03-11 18:31 UTC, aditi-khare-mongoDB approved these changes

2024-03-11 18:40 UTC, merged