remove aws temporary credential code from aws auth provider
mongodb/node-mongodb-native pull request #4050
Opened 2024-03-20 19:07 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-03-21 20:18 UTC, baileympearson commented on src/cmap/auth/aws_temporary_credentials.ts
> +export interface AWSTempCredentials {
not new - moved from `mongodb_aws.ts`.

2024-03-22 14:53 UTC, nbbeeken requested changes

2024-03-22 17:50 UTC, nbbeeken requested changes

2024-03-22 17:50 UTC, nbbeeken commented on src/error.ts
>    }
```suggestion
  constructor(message: string, options?: { cause?: Error }) {
    super(message, options);
  }
```

nit, no need to destructure just to create a new object. And `AnyError` is equivalent to `Error` here.

2024-03-22 18:45 UTC, nbbeeken requested changes

2024-03-22 18:45 UTC, nbbeeken commented on src/error.ts
> +  constructor(message: string, options: { cause?: AnyError } = {}) {
```suggestion
  constructor(message: string, options: { cause?: Error } = {}) {
```

2024-03-22 19:03 UTC, nbbeeken approved these changes

2024-03-25 13:10 UTC, merged