fix(NODE-6085): add TS support for KMIP data key options
mongodb/node-mongodb-native pull request #4128
Opened 2024-06-03 21:56 UTC by baileympearson

### Description

#### What is changing?

The original KMIP implementation added runtime support for KMIP data key options, but did not add TS support.  This PR adds support for the keyId and endpoint options, with delegated to be added in [NODE-5853](https://jira.mongodb.org/browse/NODE-5853).

Demonstration of the options working as expected: https://github.com/mongodb/node-mongodb-native/blob/db00ac46847563f7d32beb1dd4ecbf18531fd15e/test/integration/client-side-encryption/client_side_encryption.prose.test.js#L1011

##### Is there new documentation needed for these changes?

No.

#### What is the motivation for this change?

Typescript accuracy.

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-06-03 21:57 UTC, baileympearson commented on src/client-side-encryption/client_encryption.ts
> -/**
Seems like we had a duplicate `ClientEncryptionRewrapManyDataKeyProviderOptions` definition.

2024-06-04 11:56 UTC, addaleax approved these changes

2024-06-04 14:35 UTC, nbbeeken approved these changes

2024-06-04 14:36 UTC, nbbeeken requested changes
sorry, lint issue

2024-06-04 14:36 UTC, nbbeeken commented on src/client-side-encryption/client_encryption.ts
> +export interface KMIPEncryptionKeyOptions {
```
Error: src/client-side-encryption/client_encryption.ts:917:3 - (ae-forgotten-export) The symbol "KMIPEncryptionKeyOptions" needs 
```

2024-06-04 21:57 UTC, merged