fix(NODE-6241): allow `Binary` as local KMS provider key
mongodb/node-mongodb-native pull request #4160
Opened 2024-06-25 12:23 UTC by addaleax

This aligns the types with actual behavior as well as the shell's expected set of supported types.

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

Accurate TS

### Release Highlight

### The `LocalKMSProviderConfiguration`'s `key` property accepts `Binary`

A `local` KMS provider at runtime accepted a `BSON` `Binary` instance but the Typescript inaccurately only permitted `Buffer` and `string`. 

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-06-25 17:13 UTC, nbbeeken requested changes

2024-06-25 22:15 UTC, addaleax commented on src/client-side-encryption/providers/index.ts
> +  key: Binary | Buffer | string;
`Uint8Array` makes sense to me. I am, personally, not a fan of stating `TypedArray` when we're really just talking about a list of bytes – `Uint16Array` or `Int32Array` aren't really types that fit here, semantically

2024-06-26 03:13 UTC, nbbeeken commented on src/client-side-encryption/providers/index.ts
> +  key: Binary | Buffer | string;
Oh yes I agree! I messed with the lingo there, just meant uint8array being the more common (in hierarchy) than Buffer.

2024-06-26 19:47 UTC, nbbeeken approved these changes

2024-06-26 19:48 UTC, merged