feat(NODE-6090): Implement CSOT logic for connection checkout and ser…
mongodb/node-mongodb-native pull request #4268
Opened 2024-10-08 20:50 UTC by baileympearson

…ver selection### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-10-16 20:31 UTC, baileympearson commented
evergreen retry

2024-10-17 14:03 UTC, baileympearson commented
evergreen retry

2024-10-17 18:49 UTC, baileympearson commented on test/tools/runner/config.ts
> +  url(
Happy to revert.  I added this for myself while looking at `configuration.url()` and thought it might be useful to leave.

2024-10-17 23:00 UTC, durran requested changes

2024-10-18 14:25 UTC, baileympearson commented on src/cursor/aggregation_cursor.ts
> +    }
Good idea - done.  I added an abstract `ExplainableCursor` class and added the helper method there.

2024-10-18 15:11 UTC, durran approved these changes

2024-10-18 15:24 UTC, nbbeeken reviewed
bson import small fix, lgtm otherwise

2024-10-18 15:24 UTC, nbbeeken commented on src/explain.ts
> +import { type Document } from 'bson';
```suggestion
import { type Document } from './bson';
```

2024-10-18 15:58 UTC, nbbeeken approved these changes

2024-10-21 11:25 UTC, merged