NODE-6502 Use a python venv wherever we use Python in driver CI
mongodb/node-mongodb-native pull request #4322
Opened 2024-11-08 16:28 UTC by blink1073

### Description

#### What is changing?

Use scripts from drivers-evergreen-tools instead of using the system python package manager.

https://spruce.mongodb.com/version/672e33e060d13d0007e3cdb4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

##### Is there new documentation needed for these changes?

No

#### What is the motivation for this change?

Some places in Node's CI we rely on the system python/pip, which can lead to compatibility issues when we call drivers-evergreen-tools scripts and broken CI.

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-11-08 17:04 UTC, baileympearson requested changes
It might be working just because the system's Python version is compatible with the drivers-evergreen-tools version, but I do see other places where I think we need to make this change

https://github.com/mongodb/node-mongodb-native/blob/19ecf07cf418480b70d065bcaa0cc0d3ef80edc9/.evergreen/run-socks5-tests.sh#L21, for example, should be run using a python venv from drivers-evergreen-tools that has boto3 installed, right?  

There are other places hard-coded into the config file that also source this script

2024-11-08 18:59 UTC, blink1073 commented
I updated and ran again against https://github.com/mongodb-labs/drivers-evergreen-tools/pull/545.

https://spruce.mongodb.com/version/672e580262625300076c1050/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

2024-11-08 20:59 UTC, blink1073 commented
New build: https://spruce.mongodb.com/version/672e7b7543cf44000751a5cf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

2024-11-11 16:11 UTC, baileympearson approved these changes

2024-11-11 16:11 UTC, merged