chore(NODE-6426): update prod dependencies
mongodb/node-mongodb-native pull request #4323
Opened 2024-11-11 14:22 UTC by durran

### Description

Updates prod dependencies

#### What is changing?

Updates the prod dependencies to latest semver compatible versions.

##### Is there new documentation needed for these changes?

None

#### What is the motivation for this change?

NODE-6426

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-11-11 15:47 UTC, durran commented on package.json
> +    "@aws-sdk/credential-providers": "^3.687.0",
Oh good catch, I forgot about that. I will check against the runtime and update appropriately.

2024-11-11 15:54 UTC, durran commented on package.json
> +    "@aws-sdk/credential-providers": "^3.687.0",
Updated, confirmed runtime SDK is now 3.632.0

2024-11-11 16:56 UTC, nbbeeken commented on package.json
> +    "@aws-sdk/credential-providers": "^3.687.0",
Sorry if I was unclear, that was the reason in the past that we actually downgraded the AWS SDK but we should still treat AWS the same as the other peers, it cannot be upgraded until we release a major version, or we change our policy such that we can upgrade any of these.

2024-11-11 16:56 UTC, nbbeeken requested changes
for viz

2024-11-13 17:29 UTC, durran commented on package.json
> +    "@aws-sdk/credential-providers": "^3.687.0",
My mistake - I misunderstood the comment. Reverted the change.

2024-11-13 19:09 UTC, nbbeeken requested changes
Something is failing relating to snappy?

2024-11-13 23:46 UTC, durran commented
New PR: https://github.com/mongodb/node-mongodb-native/pull/4327

2024-11-13 23:46 UTC, closed without merging