test(NODE-6620): Add Improved Client.close() Socket Resource Integration Tests
mongodb/node-mongodb-native pull request #4361
Opened 2024-12-30 20:37 UTC by aditi-khare-mongoDB

### Description
Add socket integration tests for client.close(). 

#### What is changing?
Assert socket creation and clean-up through libuv tracking for each relevant driver instance of socket creation.

##### Is there new documentation needed for these changes?
No

#### What is the motivation for this change?
Improved client.close()

### Release Highlight

###

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2025-01-07 23:39 UTC, aditi-khare-mongoDB commented on test/tools/fixtures/process_resource_script.in.js
> +      !originalReportAddresses.includes(resource.address) && resource.is_referenced // if a resource is unreferenced, it's not keeping the event loop open
Follow-up from NODE-6620: We do want to clean up inactive sockets

2025-01-07 23:39 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +                // note: minPoolSizeCheckFrequencyMS = 100 ms by client, so this test has a chance of being flaky
See the note on the comment. This test has a higher chance of being flaky since the client can't set `minPoolSizeCheckFrequencyMS`. I can this to set the variable to a higher value using sinon if preferred by reviewers.

2025-01-10 21:39 UTC, nbbeeken requested changes

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                }
```suggestion
                for (const [, server] of servers) {
                  const { host, port } = server.s.description.hostAddress;
                  expect(connectionMonitoringReport()).to.deep.include({ host, port });
                }
```

Just so that the variable "server" is actually the server and not the tuple that we have to access the second item in.

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                      process.report.getReport().libuv.filter(r => r.type === 'tcp');
We made getTimerCount a shared function should we do the same for sockets?

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +              expect(client.topology.s.srvPoller._timeout).to.exist;
Can you try using the srv records in the initial seedlist spec: https://github.com/mongodb/specifications/tree/master/source/initial-dns-seedlist-discovery/tests#test-setup Those should work then we don't have to get an atlas test uri in here somehow

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                const utilClient = new MongoClient(uri);
Can you use a beforeEach/afterEach to make sure we clean up the fail point? A great way to make sure only the client in the test responds is to set an appName

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                const timeoutStartedSpy = sinon.spy(timers, 'setTimeout');
I'm seeing an error thrown for this the same way it was for the server selection test. I don't think we need the spy if we know we have a commandStarted on a client with maxPoolSize: 1

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                  minPoolSize: 1,
I would only set the max so that we don't create the timer for satisfying minPoolSize, not necessarily a problem but more resources that we need to make for this test.

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                const err = await insertPromise;
Shouldn't the first insertPromise succeed (just after a long time), its the second one that won't be able to complete connection checkout

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                  expect(connectionMonitoringReport()).to.have.length(0);
```suggestion
                  expect(connectionMonitoringReport()).to.have.lengthOf(0);
```

I could be wrong but I think you have to use lengthOf

2025-01-10 21:39 UTC, nbbeeken commented on test/integration/node-specific/client_close.test.ts
> +                const kmsProviders = mongodb.BSON.EJSON.parse(process.env.CSFLE_KMS_PROVIDERS);
This test fails locally when CSFLE_KMS_PROVIDERS isn't defined, which is the default, can you put the metadata on this test to have it skip unless encryption is enabled?

2025-01-10 22:43 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +                const err = await insertPromise;
I was confused / surprised about this as well. If we await both of them, the first one fails and the second one succeeds.

2025-01-21 22:27 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +            sinon.stub(Promise, 'race').callsFake(async ([_serverPromise, timeout]) => {
Thanks for the pointer, I added that in!

Interesting error, I'd look into it, but for the time being we're removing both of the setTimeout spy cases.

2025-01-21 22:27 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +                const timeoutStartedSpy = sinon.spy(timers, 'setTimeout');
Sounds good, replaced the spy with the awaiting a commandStarted event

2025-01-21 22:27 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +                const utilClient = new MongoClient(uri);
Yep, made the change!

2025-01-21 22:27 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +              expect(client.topology.s.srvPoller._timeout).to.exist;
I tried the set-up, seems like we don't have the [SRV environment testing case set-up ](https://github.com/mongodb/node-mongodb-native/blob/41b066b2b286879085b05a58c0486aa1d24303bc/test/integration/initial-dns-seedlist-discovery/initial_dns_seedlist_discovery.spec.test.ts#L21)(we're not running SRV spec tests as of now).

We could set it up so this test case is used for more testing envs, but given that we want to wrap up the project by tomorrow, maybe we leave setting up an SRV testing environment to a later time?

2025-01-23 16:32 UTC, aditi-khare-mongoDB commented on test/integration/node-specific/client_close.test.ts
> +                const err = await insertPromise;
Desk conversation: fixed the event awaiting

2025-01-23 17:02 UTC, nbbeeken approved these changes

2025-01-23 17:04 UTC, merged